---
version: 2.1
orbs:
  snyk: snyk/snyk@0.1.0
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - snyk/scan:
          token-variable: SNYK_TOKEN
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: high
          project: 'react-weather-app/main-app'
          protect: true
      - run: yarn test
      - run: yarn lint
      - deploy:
          name: Build
          command: npm run build
      - run:
          name: Run e2e tests
          command: npm run e2e:ci
      # e2e test result reporter
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Deploy
          command: curl -X POST -d {} ${NETLIFY_REACT_WEATHER_APP_HOOK}  