---
version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
  snyk: snyk/snyk@0.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      cache-version: v2
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages:
        pkg-manager: yarn
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - snyk/scan:
          token-variable: SNYK_TOKEN
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: high
          project: 'react-weather-app/main-app'
          protect: true
      - deploy:
          name: Build
          command: npm run build
      - run:
          command: npm run e2e:ci
      - run: npm run test
      - run: npm run lint
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - test