---
version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
  snyk: snyk/snyk@0.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages:
          pkg-manager: yarn
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock"}}
      - snyk/scan:
          token-variable: SNYK_TOKEN
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: high
          project: 'react-weather-app/main-app'
          protect: true
      - deploy:
          name: Build
          command: npm run build
      - run:
          command: npm run e2e:ci
      - run: npm run test
      - store_test_results:
          path: /tmp/test-results
      - run: npm run lint
      - run: npm run netlify:deploy
workflows:
  e2e-test:
    jobs:
      - test