version: 2.1
orbs:
  node: circleci/node@4.1.0
  browser-tools: circleci/browser-tools@1.1.0
  snyk: snyk/snyk@0.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - node_modules
            - ~/.npm 
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - snyk/scan:
          token-variable: SNYK_TOKEN
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: high
          project: 'react-weather-app/main-app'
          protect: true
      - deploy:
          name: Build
          command: npm run build
      - run:
          command: npm run e2e:ci
      - run: npm run test
      - run: npm run lint
      - store_test_results:
          path: /tmp/test-results
workflows:
  e2e-test:
    jobs:
      - test